name: al_dana
version: 1.0.4+22
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus:
  get: 4.6.5
  http:
  provider:
  get_storage: ^2.0.3
  # google_fonts: ^3.0.1
  google_fonts: 6.1.0
  flutter_svg: ^1.1.6
  permission_handler: ^10.2.0
  fluttertoast: ^8.1.1
  intl: ^0.17.0
  image_picker: ^0.8.6
  # image_cropper: ^3.0.1
  image_cropper: ^5.0.0
  file_picker: ^5.2.2
  google_maps_flutter: ^2.2.1
  # location: ^4.4.0
  # flutter_polyline_points: ^1.0.0
  # flutter_polyline_points: ^2.0.0
  map_launcher: ^2.4.0
  animated_bottom_navigation_bar: ^1.1.0
  intl_phone_field: ^3.1.0
  card_swiper: ^2.0.4
  dotted_border: ^2.0.0+3
  order_tracker: ^0.0.2
  flutter_colorpicker: ^1.0.3
  syncfusion_flutter_datepicker: ^19.4.48
  pdf:
  geocoding: ^2.0.5
  razorpay_flutter: ^1.3.4
  smooth_page_indicator: ^1.1.0
  open_file:
  path_provider:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/intro/
    - assets/auth/
